### ISSUE TITLE
Best place to discuss where this project might head?

### ISSUE THREAD

**Issue by cdbattags** [KillingSpark/rustysd#10]
Any realtime-esque way to chat about this project?

Slack? Glitter? Etc?

**Comment by KillingSpark** [comment]
I dont really have any experience how this Kind of stuff is normally handled, I will Look into it and report back :)

**Comment by KillingSpark** [comment]
I have crated a gitter community [here](https://gitter.im/rustysd/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link). It seems pretty sensible since it doesn't require a client app. Might open a discord channel if people would like that. Will add it to Readme too.

**Comment by MggMuggins** [comment]
Would be happy for a discord server, but no pressure to do so.
