### ISSUE TITLE
podman systemd service compatibility and Type=forking

### ISSUE THREAD

**Issue by pwFoo** [KillingSpark/rustysd#19]
Hi @KillingSpark 
current rustysd won't be compatible to podman generated systemd services because of `Type=forking`  and maybe other options like `PIDFile=` or `KillMode`. Maybe it would be ok to just ignore unsupported options...

Examples:
https://www.mankier.com/1/podman-generate-systemd

Maybe it's not needed to support the podman generated systemd services because it isn't really a good solution at the moment (manually create the container and generate a start / stop service... 
So if the container is removed the service won't work or regenerate I think.
But maybe run / create command could be integrated into `podman generate systemd` in the future...

Why Type=forking isn't supported? No need to implement or is it to complex?

**Comment by KillingSpark** [comment]
Type forking needs some special state keeping logic and I haven't seen a real usecase for it until now. Is it actually necessary for podman to use type forking?

**Comment by pwFoo** [comment]
So we shouldn't take care about podman generated units at the moment...
I don't like the current way it seems to work. So I need to generate custom systemd units and that should work with rustysd.
