### ISSUE TITLE
Does logging make sense?

### ISSUE THREAD

**Issue by EdorianDark** [KillingSpark/rustysd#2]
Inside a container it is probably better to push all logs outside, to Docker so so.

**Comment by KillingSpark** [comment]
Yep. The logging should have an option to just log everything to stdout. I'll implement that soon

**Comment by KillingSpark** [comment]
So with commit fc3f902e8dabecea788e10a3999df64fc429bbb4 you can configure where you want your logs to go. You can en/disable logging to stdout and to disk.
