### ISSUE TITLE
ExecStart with commands like /bin/sh -c '<CMD>'

### ISSUE THREAD

**Issue by pwFoo** [KillingSpark/rustysd#20]
Is it possible to get that command running as rustysd service?
It's a complex shell command which should(?) work with systemd.
```
ExecStart=/bin/sh -c '/bin/grep -h MODALIAS /sys/bus/*/devices/*/uevent | /usr/bin/cut -d= -f2 | /usr/bin/xargs /sbin/modprobe -abq 2> /dev/null'
```

Fails with error because of ignored `'` and `"` in the command.
```
[modules.service][STDERR] EXECV: "/bin/sh" ["sh", "-c", "\'/bin/grep", "-h", "MODALIAS", "/sys/bus/*/devices/*/uevent", "|", "/usr/bin/cut", "-d=", "-f2", "|", "/usr/bin/xargs", "/sbin/modprobe", "-abq", "2>", "/dev/null\'"]
[modules.service][STDERR] -h: line 1: syntax error: unterminated quoted string
```

**Comment by KillingSpark** [comment]
Ah that looks like a bug with the parsing of commands. I will look into how to correctly parse this. Currently rustysd splits on spaces but it should probably join again if a " or a ' is found.

**Comment by KillingSpark** [comment]
So this should be fixed now. Rustysd uses shellwords to parse these strings like bash would. This seems like what most people would expect.

**Comment by pwFoo** [comment]
Works fine for ExecStart and ExecStartPre 👍
