### ISSUE TITLE
Shutdown should honor dependencies

### ISSUE THREAD

**Issue by KillingSpark** [KillingSpark/rustysd#24]
Shutdown currently kills all services in no particular order. It should use deactivate_recursively() starting at the units that do not depend on anything.

**Comment by nimaje** [comment]
You mean 'starting at the units which aren't depended on by anything'? 
Else you would kill dependencies of running services which could lead to 
problems.

**Comment by KillingSpark** [comment]
I guess that was misleading. deactivate_recursively() already walks the dependency tree and deactivates depending units first. So you want to call it on the units that do not depend on anything and let deactivate_recursively() do its thing.

**Comment by KillingSpark** [comment]
Should be fixed with 34a4c620392aa5ac2673274c20ddee3317224ec3
