### ISSUE TITLE
macos support (osx)

### ISSUE THREAD

**Issue by zboldyga** [KillingSpark/rustysd#27]
My dev environment is macos, so expanding to add macos support it seems like a solid starting point. I tinkered a bit today and didn't resolve yet, but it may be an easy transition. Will post here with results/findings.

Also, it might be good to decide exactly which platforms are being supported in the current version. We can include these in CI tests and executable builds, and strictly-enforce them with the #[cfg]s. I'm not sure if targeting all of linux would work, there might be subtleties in the support of the nix crate, or variations in some of the supported tooling. So maybe we try:

- ubuntu
- red hat
- debian
- freebsd
- openbsd
- netbsd
- dragonfly
- macos
- windows server 2019
- windows 10

I would probably save windows support for last, mainly because I haven't used it in a long time, and I'm not sure if there's a way to spin-up containers with Windows without paying a license fee - will check that later.

**Comment by zboldyga** [comment]
@KillingSpark Just wanted to chime back in - after grappling with osx support for a few hours, I'm thinking it might be better to defer this feature until a later release. Reasons:

1. Apple has deviated from the posix API that is effectively used in linux (nix::unistd) in many ways. Commands like setresuid have an apple equivalent (setuid), but the behavior is slightly different. 'setgroups' isn't available and instead opendirectoryd should be used. And ~a dozen more cases like this. 

2. I don't have experience with apple's opendirectoryd or launchctl. If someone with experience in those areas contributes, it might be a little quicker for them to add osx support. 

Will shift my focus to general test cases & code cleanup for now :)

**Comment by KillingSpark** [comment]
Ok :) That's very good to know! Thanks for looking into that.

With windows it is probably a similar story. 

I guess going for linux + *BSDs seems as the most achievable. But we should keep in mind to not let this assumption bleed into the codebase. Rustysd should stay as generic as possible outside of the src/platform
