### ISSUE TITLE
rustybox and supervising process riffol 

### ISSUE THREAD

**Issue by pwFoo** [KillingSpark/rustysd#28]
I searched for interesting rust based Projects and found two. Not planned to use, but maybe interesting Projects to take a look in features or source...

Last commit 11 months ago. Haven't tested or looked into features / source. Just link it here to compare and maybe get some inspiration for rustysd...
https://github.com/riboseinc/riffol

Would it possible to replace rustybox init with rustysd? Build rustysd as an applet?
https://github.com/samuela/rustybox

Maybe I should start to learn rust 😅

**Comment by KillingSpark** [comment]
I dont think replacing rustybox init with rustysd is in spirit of that project. Busybox and friends normally aim for simplicity and smallness. While those are goals of rustysd too the whole concept of systemd/rustysd requires more complexity than what I'd expect from something like rustybox.

Using rustybox init to init the system and then starting rustysd seems cool though!

**Comment by pwFoo** [comment]
The idea was to have rustysd as **optional** rustybox init plugin. Not to replace the native init plugin. 

I have trouble to build rustybox and busybox (static) works fine for my custom and minimal host setup.

I close the issue because isn't a issue. It just was a short discussion ;)
