### ISSUE TITLE
command source unclear

### ISSUE THREAD

**Issue by EdorianDark** [KillingSpark/rustysd#3]
The with accept_control_connections commands are accepted.
But i do not understand where they are coming from.
Can you help?

**Comment by KillingSpark** [comment]
The plan there was to have rustysd listen on a unix socket / tcp socket and receive commands from a secondary tool (roughly equivalent to systemctl).
This part is still very much in it's concept stage but will be built out in the future

**Comment by EdorianDark** [comment]
Ok, thank you
