### ISSUE TITLE
Container based OS: busybox + rustysd + crun + gpm build with linuxkit

### ISSUE THREAD

**Issue by pwFoo** [KillingSpark/rustysd#30]
Build initrd+kernel with linuxkit.
Init is based on busybox init (prepare host, generate unitfiles without dependencies for now...) and rustysd (start linuxkit services).

all dockerfiles, linuxkit yml is included here:
https://github.com/pwFoo/DenglerOS

```
/ # crun list
NAME   PID       STATUS   BUNDLE PATH                            
rngd   693       running  /containers/services/rngd              
docker 694       running  /containers/services/docker            
udhcpc 695       running  /containers/services/udhcpc            
mdevd  696       running  /containers/services/mdevd             
```

```
/ # rsdctl /notifications/control.socket status
Write cmd: {"jsonrpc":"2.0","method":"status"}
[2020-02-22][16:53:17][rustysd::control::control][TRACE] Execute command: Status(None)
Wait for response
Got response
{
  "jsonrpc": "2.0",
  "result": [
    {
      "Name": "init.target",
      "Status": "Started"
    },
    {
      "Name": "rngd.service",
      "Restarted": "0",
      "Sockets": [],
      "Status": "Started",
      "UpSince": "65.858849801s"
    },
    {
      "Name": "onboot.target",
      "Status": "Started"
    },
    {
      "Name": "network.target",
      "Status": "Started"
    },
    {
      "Name": "docker.service",
      "Restarted": "0",
      "Sockets": [],
      "Status": "Started",
      "UpSince": "65.783275025s"
    },
    {
      "Name": "mdevd.service",
      "Restarted": "0",
      "Sockets": [],
      "Status": "Started",
      "UpSince": "65.73633628s"
    },
    {
      "Name": "default.target",
      "Status": "Started"
    },
    {
      "Name": "udhcpc.service",
      "Restarted": "0",
      "Sockets": [],
      "Status": "Started",
      "UpSince": "65.75102832s"
    },
    {
      "Name": "services.target",
      "Status": "Started"
    }
  ]
}
```

@KillingSpark @cdbattags @justincormack 

#13 #15

**Comment by pwFoo** [comment]
Run docker container from host:
```
crun exec -ti docker docker run --rm -ti alpine sh
```

**Comment by KillingSpark** [comment]
This is really cool! Are you running this in a VM?

**Comment by pwFoo** [comment]
Tested with qemu and dell notebook.

**Comment by pwFoo** [comment]
Added dropbear sshd for some custom needs (connect from remote workstation)...

Everyone who wants to help improve the system and make it usable is welcome!

In the past I created docker images for xorg, fluxbox, chromium, ... and I could update and provide them.

**Comment by pwFoo** [comment]
I done a rewrite of my build script for my custom fun linux called "DenglerOS"...
It would need improvements and clean up script code... but it works with first tests.

**build script:** https://github.com/dengleros/dosctl
**example yml:** https://github.com/dengleros/DenglerOS/blob/master/dengleros.yml

**Some first examples from readme file.**

# build os

dosctl installed to your PATH, change to a (empty) working directory and build kernel+initrd
```
dosctl os <YML-FILE>
dosctl <YML-FILE>
```

# run os

Execute from the same working directory as above. YML-File or project name (YML file name without extension). Local installed qemu is needed.
```
dosctl run <YML-FILE>
```

# Build docker image

```
dosctl img dengleros/os-rustysd:latest -build -push
```
# services in container

All services run in crun container.
```
/ # crun list 
NAME   PID       STATUS   BUNDLE PATH                            
rngd   825       running  /containers/services/rngd              
udhcpc 826       running  /containers/services/udhcpc            
mdevd  827       running  /containers/services/mdevd             
sshd   824       running  /containers/services/sshd
```

# gpm package manager

Successfully booted DenglerOS try to install example package
```
gpm update
gpm install docker
/prepare.sh /containers/services/docker  # workaround to update unitfile... without trailing "/"!!!
rsdctl /notifications/control.socket reload  # update / add new service to rustysd
rsdctl /notifications/control.socket restart docker.service   # (re-)start service "docker"
crun exec -t docker docker run --rm -ti alpine sh   # :)
```

**Comment by KillingSpark** [comment]
I love the idea of having all services in their respective crun container instead of having rustysd do all that work (like systemd decided to do it)

**Comment by pwFoo** [comment]
Restart unit seems to be a problem. Maybe because of the time needed to stop a running crun container. 
But I like the base. Works fine. But would need some improvements and extensions...

**Comment by KillingSpark** [comment]
Could you describe more what problems arise when restarting a unit?

**Comment by pwFoo** [comment]
First I try to optimize and do some more tests ;)
