### ISSUE TITLE
Docker PID 1

### ISSUE THREAD

**Issue by xavier83** [KillingSpark/rustysd#9]
Can it be used as a replacement for https://github.com/Yelp/dumb-init inside a docker container?

**Comment by KillingSpark** [comment]
So the current Plan is to Support this usecase. But i dont want to promise anything for the future

**Comment by KillingSpark** [comment]
Ok, so I was able to run the current tests services in docker using rustysd as the entrypoint, so I would assume you could use rustysd as a replacement of dumb-init. 

If there arise any issues from using it as pid1 in a docker container please let me know!
